[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "aarch64-nintendo-switch-freestanding"
rustflags = ["-C", "link-args=--init init"]
